# Generated by Django 4.0.3 on 2022-12-12 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transactions_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='wallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='wallets_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='wallets_balances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.wallets')),
            ],
        ),
        migrations.AddField(
            model_name='wallets',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.wallets_types'),
        ),
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('sum', models.IntegerField()),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.transactions_types')),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.wallets')),
            ],
        ),
    ]
