from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_menu_window(object):
    def setupUi(self, main_menu_window):
        main_menu_window.setObjectName("main_menu_window")
        main_menu_window.resize(360, 210)
        main_menu_window.setMaximumSize(QtCore.QSize(360, 210))
        main_menu_window.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(main_menu_window)
        self.centralwidget.setObjectName("centralwidget")
        self.main_menu_label = QtWidgets.QLabel(self.centralwidget)
        self.main_menu_label.setGeometry(QtCore.QRect(0, 0, 360, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.main_menu_label.setFont(font)
        self.main_menu_label.setAlignment(QtCore.Qt.AlignCenter)
        self.main_menu_label.setObjectName("main_menu_label")
        self.transactions_button = QtWidgets.QPushButton(self.centralwidget)
        self.transactions_button.setGeometry(QtCore.QRect(40, 60, 280, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.transactions_button.setFont(font)
        self.transactions_button.setObjectName("transactions_button")
        self.wallets_button = QtWidgets.QPushButton(self.centralwidget)
        self.wallets_button.setGeometry(QtCore.QRect(40, 110, 280, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.wallets_button.setFont(font)
        self.wallets_button.setObjectName("wallets_button")
        self.settings_button = QtWidgets.QPushButton(self.centralwidget)
        self.settings_button.setGeometry(QtCore.QRect(40, 160, 280, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.settings_button.setFont(font)
        self.settings_button.setObjectName("settings_button")
        main_menu_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(main_menu_window)
        QtCore.QMetaObject.connectSlotsByName(main_menu_window)

    def retranslateUi(self, main_menu_window):
        _translate = QtCore.QCoreApplication.translate
        main_menu_window.setWindowTitle(_translate("main_menu_window", "MainWindow"))
        self.main_menu_label.setText(_translate("main_menu_window", "Главное меню"))
        self.transactions_button.setText(_translate("main_menu_window", "Транзакции"))
        self.wallets_button.setText(_translate("main_menu_window", "Кошельки"))
        self.settings_button.setText(_translate("main_menu_window", "Настройки"))

class Ui_transaction_window(object):
    def setupUi(self, transaction_window):
        transaction_window.setObjectName("transaction_window")
        transaction_window.resize(360, 229)
        transaction_window.setMaximumSize(QtCore.QSize(360, 250))
        self.centralwidget = QtWidgets.QWidget(transaction_window)
        self.centralwidget.setObjectName("centralwidget")
        self.transaction_label = QtWidgets.QLabel(self.centralwidget)
        self.transaction_label.setGeometry(QtCore.QRect(0, 0, 360, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.transaction_label.setFont(font)
        self.transaction_label.setAlignment(QtCore.Qt.AlignCenter)
        self.transaction_label.setObjectName("transaction_label")
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setGeometry(QtCore.QRect(40, 180, 280, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.save_button.setFont(font)
        self.save_button.setObjectName("save_button")
        self.summ_label = QtWidgets.QLabel(self.centralwidget)
        self.summ_label.setGeometry(QtCore.QRect(31, 80, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.summ_label.setFont(font)
        self.summ_label.setObjectName("summ_label")
        self.summ_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.summ_line_edit.setGeometry(QtCore.QRect(110, 80, 221, 20))
        self.summ_line_edit.setObjectName("summ_line_edit")
        self.transaction_type_label = QtWidgets.QLabel(self.centralwidget)
        self.transaction_type_label.setGeometry(QtCore.QRect(30, 110, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.transaction_type_label.setFont(font)
        self.transaction_type_label.setObjectName("transaction_type_label")
        self.transaction_type_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.transaction_type_combo_box.setGeometry(QtCore.QRect(190, 110, 141, 22))
        self.transaction_type_combo_box.setObjectName("transaction_type_combo_box")
        self.wallet_label = QtWidgets.QLabel(self.centralwidget)
        self.wallet_label.setGeometry(QtCore.QRect(30, 140, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.wallet_label.setFont(font)
        self.wallet_label.setObjectName("wallet_label")
        self.wallet_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.wallet_combo_box.setGeometry(QtCore.QRect(130, 140, 201, 22))
        self.wallet_combo_box.setObjectName("wallet_combo_box")
        self.id_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.id_line_edit.setGeometry(QtCore.QRect(69, 50, 261, 20))
        self.id_line_edit.setText("")
        self.id_line_edit.setReadOnly(True)
        self.id_line_edit.setObjectName("id_line_edit")
        self.id_label = QtWidgets.QLabel(self.centralwidget)
        self.id_label.setGeometry(QtCore.QRect(30, 50, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.id_label.setFont(font)
        self.id_label.setObjectName("id_label")
        transaction_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(transaction_window)
        QtCore.QMetaObject.connectSlotsByName(transaction_window)

    def retranslateUi(self, transaction_window):
        _translate = QtCore.QCoreApplication.translate
        transaction_window.setWindowTitle(_translate("transaction_window", "MainWindow"))
        self.transaction_label.setText(_translate("transaction_window", "Транзакция"))
        self.save_button.setText(_translate("transaction_window", "Сохранить"))
        self.summ_label.setText(_translate("transaction_window", "Сумма:"))
        self.transaction_type_label.setText(_translate("transaction_window", "Вид транзакции:"))
        self.wallet_label.setText(_translate("transaction_window", "Кошелёк:"))
        self.id_label.setText(_translate("transaction_window", "ID:"))


    def retranslateUi(self, new_transaction_window):
        _translate = QtCore.QCoreApplication.translate
        new_transaction_window.setWindowTitle(_translate("new_transaction_window", "MainWindow"))
        self.new_transaction_label.setText(_translate("new_transaction_window", "Новая транзакция"))
        self.save_button.setText(_translate("new_transaction_window", "Сохранить"))
        self.summ_label.setText(_translate("new_transaction_window", "Сумма:"))
        self.transaction_type_label.setText(_translate("new_transaction_window", "Вид транзакции:"))
        self.wallet_label.setText(_translate("new_transaction_window", "Кошелёк:"))

class Ui_wallet_window(object):
    def setupUi(self, wallet_window):
        wallet_window.setObjectName("wallet_window")
        wallet_window.resize(360, 214)
        wallet_window.setMaximumSize(QtCore.QSize(360, 214))
        self.centralwidget = QtWidgets.QWidget(wallet_window)
        self.centralwidget.setObjectName("centralwidget")
        self.wallet_label = QtWidgets.QLabel(self.centralwidget)
        self.wallet_label.setGeometry(QtCore.QRect(0, 0, 360, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.wallet_label.setFont(font)
        self.wallet_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wallet_label.setObjectName("wallet_label")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(20, 90, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.title_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.title_line_edit.setGeometry(QtCore.QRect(120, 90, 221, 20))
        self.title_line_edit.setObjectName("title_line_edit")
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setGeometry(QtCore.QRect(40, 160, 280, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.save_button.setFont(font)
        self.save_button.setObjectName("save_button")
        self.id_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.id_line_edit.setGeometry(QtCore.QRect(60, 60, 281, 20))
        self.id_line_edit.setText("")
        self.id_line_edit.setObjectName("id_line_edit")
        self.id_label = QtWidgets.QLabel(self.centralwidget)
        self.id_label.setGeometry(QtCore.QRect(20, 60, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.id_label.setFont(font)
        self.id_label.setObjectName("id_label")
        self.wallet_type_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.wallet_type_combo_box.setGeometry(QtCore.QRect(70, 120, 271, 22))
        self.wallet_type_combo_box.setObjectName("wallet_type_combo_box")
        self.wallet_type_label = QtWidgets.QLabel(self.centralwidget)
        self.wallet_type_label.setGeometry(QtCore.QRect(20, 120, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.wallet_type_label.setFont(font)
        self.wallet_type_label.setObjectName("wallet_type_label")
        wallet_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(wallet_window)
        QtCore.QMetaObject.connectSlotsByName(wallet_window)

    def retranslateUi(self, wallet_window):
        _translate = QtCore.QCoreApplication.translate
        wallet_window.setWindowTitle(_translate("wallet_window", "MainWindow"))
        self.wallet_label.setText(_translate("wallet_window", "Кошелёк"))
        self.title_label.setText(_translate("wallet_window", "Название:"))
        self.save_button.setText(_translate("wallet_window", "Сохранить"))
        self.id_label.setText(_translate("wallet_window", "ID:"))
        self.wallet_type_label.setText(_translate("wallet_window", "Тип:"))

class Ui_settings_window(object):
    def setupUi(self, settings_window):
        settings_window.setObjectName("settings_window")
        settings_window.resize(360, 120)
        settings_window.setMaximumSize(QtCore.QSize(360, 120))
        self.centralwidget = QtWidgets.QWidget(settings_window)
        self.centralwidget.setObjectName("centralwidget")
        self.settings_label = QtWidgets.QLabel(self.centralwidget)
        self.settings_label.setGeometry(QtCore.QRect(0, 0, 360, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.settings_label.setFont(font)
        self.settings_label.setAlignment(QtCore.Qt.AlignCenter)
        self.settings_label.setObjectName("settings_label")
        self.clear_base_button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_base_button.setGeometry(QtCore.QRect(40, 60, 280, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.clear_base_button.setFont(font)
        self.clear_base_button.setObjectName("clear_base_button")
        settings_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(settings_window)
        QtCore.QMetaObject.connectSlotsByName(settings_window)

    def retranslateUi(self, settings_window):
        _translate = QtCore.QCoreApplication.translate
        settings_window.setWindowTitle(_translate("settings_window", "MainWindow"))
        self.settings_label.setText(_translate("settings_window", "Настройки"))
        self.clear_base_button.setText(_translate("settings_window", "Очистить базу"))

class Ui_transactions_window(object):
    def setupUi(self, transactions_window):
        transactions_window.setObjectName("transactions_window")
        transactions_window.resize(360, 530)
        transactions_window.setMaximumSize(QtCore.QSize(360, 530))
        self.centralwidget = QtWidgets.QWidget(transactions_window)
        self.centralwidget.setObjectName("centralwidget")
        self.transactions_label = QtWidgets.QLabel(self.centralwidget)
        self.transactions_label.setGeometry(QtCore.QRect(0, 0, 360, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.transactions_label.setFont(font)
        self.transactions_label.setAlignment(QtCore.Qt.AlignCenter)
        self.transactions_label.setObjectName("transactions_label")
        self.create_transaction_button = QtWidgets.QPushButton(self.centralwidget)
        self.create_transaction_button.setGeometry(QtCore.QRect(40, 50, 280, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.create_transaction_button.setFont(font)
        self.create_transaction_button.setObjectName("create_transaction_button")
        self.transactions_list = QtWidgets.QListWidget(self.centralwidget)
        self.transactions_list.setGeometry(QtCore.QRect(40, 100, 280, 360))
        self.transactions_list.setObjectName("transactions_list")
        self.delete_transaction_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_transaction_button.setGeometry(QtCore.QRect(40, 470, 280, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.delete_transaction_button.setFont(font)
        self.delete_transaction_button.setObjectName("delete_transaction_button")
        transactions_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(transactions_window)
        QtCore.QMetaObject.connectSlotsByName(transactions_window)

    def retranslateUi(self, transactions_window):
        _translate = QtCore.QCoreApplication.translate
        transactions_window.setWindowTitle(_translate("transactions_window", "MainWindow"))
        self.transactions_label.setText(_translate("transactions_window", "Транзакции"))
        self.create_transaction_button.setText(_translate("transactions_window", "Создать транзакцию"))
        self.delete_transaction_button.setText(_translate("transactions_window", "Удалить транзакцию"))

class Ui_wallets_window(object):
    def setupUi(self, wallets_window):
        wallets_window.setObjectName("wallets_window")
        wallets_window.resize(360, 530)
        wallets_window.setMaximumSize(QtCore.QSize(360, 530))
        self.centralwidget = QtWidgets.QWidget(wallets_window)
        self.centralwidget.setObjectName("centralwidget")
        self.wallets_label = QtWidgets.QLabel(self.centralwidget)
        self.wallets_label.setGeometry(QtCore.QRect(0, 0, 360, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.wallets_label.setFont(font)
        self.wallets_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wallets_label.setObjectName("wallets_label")
        self.create_wallet_button = QtWidgets.QPushButton(self.centralwidget)
        self.create_wallet_button.setGeometry(QtCore.QRect(40, 50, 280, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.create_wallet_button.setFont(font)
        self.create_wallet_button.setObjectName("create_wallet_button")
        self.wallets_list = QtWidgets.QListWidget(self.centralwidget)
        self.wallets_list.setGeometry(QtCore.QRect(40, 100, 280, 360))
        self.wallets_list.setObjectName("wallets_list")
        self.delete_wallet_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_wallet_button.setGeometry(QtCore.QRect(40, 470, 280, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.delete_wallet_button.setFont(font)
        self.delete_wallet_button.setObjectName("delete_wallet_button")
        wallets_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(wallets_window)
        QtCore.QMetaObject.connectSlotsByName(wallets_window)

    def retranslateUi(self, wallets_window):
        _translate = QtCore.QCoreApplication.translate
        wallets_window.setWindowTitle(_translate("wallets_window", "MainWindow"))
        self.wallets_label.setText(_translate("wallets_window", "Кошельки"))
        self.create_wallet_button.setText(_translate("wallets_window", "Создать кошелёк"))
        self.delete_wallet_button.setText(_translate("wallets_window", "Удалить кошелёк"))
